project:
  type: website

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: true
    toc-depth: 3

execute:
  freeze: auto

website:
  search: true
  title: "Active Matter Physics"
  page-navigation: true
  navbar:
    background: primary
    search: true
    right:
      - icon: github
  sidebar:
    style: "floating" # Options: "floating", "sticky"
    logo: assets/images/mona_logo.png
    collapse-level: 3
    contents:
      - text: Home
        href: index.qmd
      - text: "---" # This creates a divider
      - section: "Course Info"
        contents:
          - text: Instructors
            href: course-info/intructors.qmd
          - text: Resources
            href: course-info/resources.qmd
          - text: Course Schedule
            href: course-info/schedule.qmd
          - text: Exam
            href: course-info/exam.qmd
      - text: "---" # This creates a divider
      - text: "Part I" # Foundations and Theoretical Framework
      - section: "Introduction to Active Matter"
        contents:
          - text: Lecture 1
            href: lecture01/lecture01.qmd
